### ISSUE TITLE
Start Transaction

### ISSUE THREAD

**Issue by BurakOgutken** [fabyr/ocpp-sharp#1]
Hi
Can you give an example for start transaction

thanks

**Comment by fabyr** [comment]
Hello,

if you want to send a **StartTransaction** (or any request originating from the chargepoint), refer to the client example in [/ocpp-sharp.examples/client](https://github.com/fabyr/ocpp-sharp/blob/826832991da2711847a38ecf59d999744717f04c/ocpp-sharp.examples/client/Program.cs#L40).

Here is the minimal example required for this:
```cs
// "client" is your instance of OcppSharpClient

// Send a start transaction request to the backend server
var responseObject = await client.SendRequestAsync(new StartTransactionRequest()
{
    connectorId = 0,
    // fill your values
});

var payload = responseObject.Payload as StartTransactionResponse;

// Example output
Console.WriteLine($"Transaction-ID: {payload!.transactionId}");
```

If you want to receive a **StartTransaction** as the backend server (or any other request), refer to the server example in [/ocpp-sharp.examples/server](https://github.com/fabyr/ocpp-sharp/blob/826832991da2711847a38ecf59d999744717f04c/ocpp-sharp.examples/server/Program.cs#L28).

This would be the code that accomplishes that for **StartTransaction**:
```cs
// "server" is your instance of OcppSharpServer
server.RegisterHandler<StartTransactionRequest>((server, sender, req) => 
{
    // Example outputs
    Console.WriteLine($"Received StartTransaction!");
    Console.WriteLine($"ConnectorId: {req.connectorId}");
    Console.WriteLine($"Meter Start: {req.meterStart}");
    // ...

    // Always need to send a response
    return new StartTransactionResponse()
    {
        transactionId = ... // fill your values
    };
});
```

I hope this answers your questions. (:
